name: 京喜工厂

on:
  workflow_dispatch:
  schedule:
    - cron: '1/2 0-23/1 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_dreamFactory

jobs:
  # timeout-minutes: 50
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 替换
        run: |
          sed -i 's/process.exit(0)/{}/g' ./src/jd_dreamFactory.js
          sed -i 's/GITHUB/G1THU8/g' ./src/jdCookie.js
      - name: '运行 【京喜工厂】'
        timeout-minutes: 50
        run: |
          node ./src/jd_dreamFactory.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE || github.event.client_payload.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG || github.event.client_payload.JD_DEBUG }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT || github.event.client_payload.JD_USER_AGENT }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
          DREAMFACTORY_NOTIFY_CONTROL: ${{ secrets.DREAMFACTORY_NOTIFY_CONTROL || github.event.client_payload.DREAMFACTORY_NOTIFY_CONTROL }}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES || github.event.client_payload.DREAM_FACTORY_SHARE_CODES }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
