name: 东东农场

on:
  workflow_dispatch:
  schedule:
    - cron: '1 4-22/1 *  * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_fruit

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: giaomaker/zhu-10
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: 替换
        run: |
          sed -i 's/process.exit(0)/{}/g' ./src/jd_fruit.js
          sed -i 's/GITHUB/G1THU8/g' ./src/jdCookie.js
      - name: '运行 【东东农场】'
        timeout-minutes: 50
        run: |
          node ./src/jd_fruit.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE || github.event.client_payload.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG || github.event.client_payload.JD_DEBUG }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT || github.event.client_payload.JD_USER_AGENT }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
          FRUITSHARECODES: ${{ secrets.FruitShareCodes || github.event.client_payload.FruitShareCodes }}
          FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD || github.event.client_payload.FRUIT_BEAN_CARD }}
          FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL || github.event.client_payload.FRUIT_NOTIFY_CONTROL }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
